spring:
  datasource:
    url: jdbc:mysql://119.3.219.4:3306/ors?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
    password: wang123
    username: root
  resources:
    static-locations: classpath:/static/
  cache: false