spring:
  devtools:
    restart:
      enabled: true #开始热部署
  freemarker:
    cache: false #页面不缓存
  datasource:
    url: jdbc:mysql://119.3.219.4:3306/ors?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.jdbc.Driver
    password: wang123
    username: root
    type: com.zaxxer.hikari.HikariDataSource
  resources:
    static-locations: classpath:/static/
  cache: false