spring:
  datasource:
   url: jdbc:mysql://localhost:3306/ors?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
   driverClassName: com.mysql.jdbc.Driver
   username: root
   password: root
